development:
  cloudinary_cloud_name: cloud_name
  cloudinary_api_key: abc123
  cloudinary_api_secret: abc123
  facebook_app_id: abc123
  google_analytics_id: abc123
production:
  cloudinary_cloud_name: cloud_name
  cloudinary_api_key: abc123
  cloudinary_api_secret: abc123
  facebook_app_id: abc123
  google_analytics_id: abc123
test:
  cloudinary_cloud_name: cloud_name
  cloudinary_api_key: abc123
  cloudinary_api_secret: abc123
  facebook_app_id: abc123
  google_analytics_id: abc123