development:
  cloud_name: <%= AppConfig["cloudinary_cloud_name"] %>
  api_key: <%= AppConfig["cloudinary_api_key"] %>
  api_secret: <%= AppConfig["cloudinary_api_secret"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= AppConfig["cloudinary_cloud_name"] %>
  api_key: <%= AppConfig["cloudinary_api_key"] %>
  api_secret: <%= AppConfig["cloudinary_api_secret"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= AppConfig["cloudinary_cloud_name"] %>
  api_key: <%= AppConfig["cloudinary_api_key"] %>
  api_secret: <%= AppConfig["cloudinary_api_secret"] %>
  enhance_image_tag: true
  static_image_support: false